apiVersion: v1alpha
kind: Project
metadata:
  name: semaphore-demo-python-django
spec:
  repository:
    url: "git@github.com:nlou9/semaphore-demo-python-django.git"
    run: true
    run_on:
      - branches
      - tags
    pipeline_file: ".semaphore/semaphore.yml"
    status:
      pipeline_files:
        - path: ".semaphore/semaphore.yml"
          level: "pipeline"
